### ISSUE TITLE
issue template

### ISSUE THREAD

**Issue by boyeborg** [boyeborg/spritz#20]
We should have a template for writing issues. Related: #17

**Comment by hgvanpariya** [comment]
@siddise , do you want the same template ?

**Comment by siddise** [comment]
I have been thinking about this. Maybe we don't need a issue template. @boyeborg what do you think?

**Comment by boyeborg** [comment]
I think I agree. Having an issue template might just raising the bar of creating an issue. A issue don't need any structure og guidelines aside from being understandable. I'll close this issue for now, and we can reopen it if we see the need for a template in the future.

**Comment by boyeborg** [comment]
Thanks anyway for the interest @hgvanpariya ✨
