### ISSUE TITLE
badges are slow

### ISSUE THREAD

**Issue by boyeborg** [boyeborg/spritz#23]
The badges are really slow to load. I suspect this is because we use shields.io badges. Perhaps using badges directly from the different providers would be faster?

**Comment by siddise** [comment]
On it!

**Comment by boyeborg** [comment]
@siddise If you need the badges:

[![Build Status](https://travis-ci.org/boyeborg/spritz.svg?branch=master)](https://travis-ci.org/boyeborg/spritz)
[![codecov](https://codecov.io/gh/boyeborg/spritz/branch/master/graph/badge.svg)](https://codecov.io/gh/boyeborg/spritz)
[![JitPack](https://jitpack.io/v/boyeborg/spritz.svg)](https://jitpack.io/#boyeborg/spritz)
